name: dakar_bus
description: Application de suivi des transports à Dakar.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
