nom : Déploiement sur GitHub Pages

sur :
  pousser :
    branches :
      - principal

autorisations :
  contenu : read
  pages : write
  jeton d'identification : write

concurrence :
  groupe : 'pages'
  annulation en cours : vrai

emplois :
  construire :
    fonctionne sous : ubuntu-latest
    étapes :
      - nom : Caisse
        utilisations : actions/checkout@v4

      - nom : Configurer Java
        utilise : actions/setup-java@v4
        avec :
          distribution : 'temurin'
          version Java : '17'

      - nom : Configurer Flutter
        utilise : subosito/flutter-action@v2
        avec :
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      - nom : Installer les dépendances
        exécuter : flutter pub get

      - nom : Créer un site web
        exécuter : |
          flutter build web --release --base-href "/dakar-bus/"

      - nom : Artefact de téléchargement de pages
        utilisations : actions/upload-pages-artifact@v3
        avec :
          chemin : build/web

  déployer :
    besoins : construire
    fonctionne sous : ubuntu-latest
    environnement :
      nom : github-pages
      url : ${{ steps.deployment.outputs.page_url }}
    étapes :
      - nom : Déployer sur GitHub Pages
        id : déploiement
        utilisations : actions/deploy-pages@v4
